<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * WOPI host coverage matrix. Not a test file - read by tests/spec-coverage.php.
 *
 * status: tested | implemented-untested | not-implemented | n-a
 *   - tested: a named, existing automated test covers this row. The 'test' field
 *     must point at a real test method or this row is lying.
 *   - implemented-untested: the behavior exists in lib/ (manually verified via curl
 *     in WOPI_TEST_RESULTS.md, 2026-05-23, or confirmed by direct code reading) but
 *     no automated test covers it yet.
 *   - not-implemented: this app does not implement this MS-WOPI operation/feature at all.
 *   - n-a: not a WOPI-spec requirement (app-specific plumbing seeded from
 *     WOPI_TEST_RESULTS.md anyway, per plan).
 *
 * Seeded from WOPI_TEST_RESULTS.md (21 numbered rows + 2 unnumbered checks, verified
 * count - see wopi-test-suite.md Environment facts) plus direct reading of
 * lib/Controller/WopiController.php, lib/Service/DiscoveryService.php,
 * lib/BackgroundJob/CleanupJob.php for code paths the manual curl pass didn't hit.
 */

return [
	// --- CheckFileInfo ---
	['id' => 'CFI-200-metadata', 'op' => 'CheckFileInfo', 'requirement' => 'GET /wopi/files/{id} with a valid token returns 200 + metadata JSON', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testCheckFileInfoReturnsMetadataForValidToken', 'notes' => 'WOPI_TEST_RESULTS.md row 1'],
	['id' => 'CFI-401-expired-token', 'op' => 'CheckFileInfo', 'requirement' => 'CheckFileInfo with an expired token returns 401', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'tested', 'test' => 'integration/CleanupJobTest::testCheckFileInfoReturns401ForExpiredToken', 'notes' => 'WOPI_TEST_RESULTS.md row 6 (combined 401/403, tested via mapper only, not HTTP-level)'],
	['id' => 'CFI-403-unknown-token', 'op' => 'CheckFileInfo', 'requirement' => 'CheckFileInfo with an unknown token returns 403', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testCheckFileInfoReturns403ForUnknownToken', 'notes' => 'WOPI_TEST_RESULTS.md row 6 (combined 401/403, tested via mapper only, not HTTP-level)'],
	['id' => 'CFI-403-fileid-mismatch', 'op' => 'CheckFileInfo', 'requirement' => 'CheckFileInfo returns 403 when the token\'s fileId does not match the requested {fileId}', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived, WopiController::checkFileInfo'],
	['id' => 'CFI-404-file-not-found', 'op' => 'CheckFileInfo', 'requirement' => 'CheckFileInfo returns 404 when the underlying file cannot be resolved', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'CFI-500-unexpected-error', 'op' => 'CheckFileInfo', 'requirement' => 'CheckFileInfo returns 500 on unexpected exceptions', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'CFI-guest-display-name', 'op' => 'CheckFileInfo', 'requirement' => 'Guest tokens show a display name and IsAnonymousUser=true', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'CFI-canwrite-false-on-foreign-lock', 'op' => 'CheckFileInfo', 'requirement' => 'UserCanWrite is forced false when an ILockManager file lock is held by a different owner', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'CFI-postmessageorigin', 'op' => 'CheckFileInfo', 'requirement' => 'PostMessageOrigin reflects the serverHost captured at token creation', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'CFI-hidedownload-flags', 'op' => 'CheckFileInfo', 'requirement' => 'HideExportOption/DisablePrint/DisableExport all follow hideDownload', 'spec' => 'MS-WOPI CheckFileInfo', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'commit d7ff5c6'],

	// --- GetFile ---
	['id' => 'GF-200-binary-body', 'op' => 'GetFile', 'requirement' => 'GET /wopi/files/{id}/contents with a valid token returns 200 + binary body', 'spec' => 'MS-WOPI GetFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testGetFileReturnsBinaryBody', 'notes' => 'WOPI_TEST_RESULTS.md row 2'],
	['id' => 'GF-206-range', 'op' => 'GetFile', 'requirement' => 'Range: bytes=0-99 returns 206 with correct Content-Range', 'spec' => 'MS-WOPI GetFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testGetFileRangeReturnsPartialContent', 'notes' => 'WOPI_TEST_RESULTS.md row 3'],
	['id' => 'GF-416-range-beyond-eof', 'op' => 'GetFile', 'requirement' => 'A Range beyond EOF returns 416 + Content-Range: bytes */{size}', 'spec' => 'MS-WOPI GetFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testGetFileRangeBeyondEofReturns416', 'notes' => 'WOPI_TEST_RESULTS.md row 4'],
	['id' => 'GF-206-range-open-ended', 'op' => 'GetFile', 'requirement' => 'Range: bytes=N- (no explicit end) returns 206 through EOF', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'GF-401-expired-token', 'op' => 'GetFile', 'requirement' => 'GetFile with an expired token returns 401', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'GF-403-unknown-token', 'op' => 'GetFile', 'requirement' => 'GetFile with an unknown token returns 403', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'GF-403-fileid-mismatch', 'op' => 'GetFile', 'requirement' => 'GetFile returns 403 when the token\'s fileId does not match {fileId}', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'GF-404-file-not-found', 'op' => 'GetFile', 'requirement' => 'GetFile returns 404 when the underlying file cannot be resolved', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'GF-empty-file-200', 'op' => 'GetFile', 'requirement' => 'GetFile on a zero-byte file returns 200 with an empty body, skipping range handling', 'spec' => 'MS-WOPI GetFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],

	// --- PutFile ---
	['id' => 'PF-200-with-correct-lock', 'op' => 'PutFile', 'requirement' => 'PutFile with the correct X-WOPI-Lock returns 200 + LastModifiedTime', 'spec' => 'MS-WOPI PutFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testPutFileWithCorrectLockSucceeds', 'notes' => 'WOPI_TEST_RESULTS.md row 15'],
	['id' => 'PF-409-wrong-lock', 'op' => 'PutFile', 'requirement' => 'PutFile without the matching X-WOPI-Lock on a locked file returns 409 + X-WOPI-Lock + X-WOPI-LockFailureReason', 'spec' => 'MS-WOPI PutFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testPutFileWithoutMatchingLockReturns409', 'notes' => 'WOPI_TEST_RESULTS.md row 14'],
	['id' => 'PF-409-item-version-mismatch', 'op' => 'PutFile', 'requirement' => 'PutFile with a stale X-WOPI-ItemVersion returns 409 + current X-WOPI-ItemVersion', 'spec' => 'MS-WOPI PutFile', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testPutFileWithStaleItemVersionReturns409', 'notes' => 'WOPI_TEST_RESULTS.md row 16'],
	['id' => 'PF-200-empty-file-no-lock-required', 'op' => 'PutFile', 'requirement' => 'PutFile on an empty file with no lock held returns 200', 'spec' => 'MS-WOPI PutFile §3.3.5.3', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testPutFileOnEmptyFileWithNoLockSucceeds', 'notes' => 'RESOLVED (was flagged as possibly stale in Task 3): WOPI_TEST_RESULTS.md row 5 predates the H-3 lock-required fix (commit 71e4f08) by 2 days. Verified live in Task 6: row 5 only holds for an EMPTY file - a non-empty file with no lock now returns 409 (see PF-409-lock-required-for-nonempty-save), confirmed by both a live curl probe and testPutFileOnNonEmptyFileWithNoLockReturns409.'],
	['id' => 'PF-409-lock-required-for-nonempty-save', 'op' => 'PutFile', 'requirement' => 'PutFile on a non-empty file with no active lock returns 409 (a lock is required before saving non-empty content)', 'spec' => 'MS-WOPI PutFile §3.3.5.3', 'status' => 'tested', 'test' => 'integration/WopiProtocolTest::testPutFileOnNonEmptyFileWithNoLockReturns409', 'notes' => 'H-3 fix, commit 71e4f08'],
	['id' => 'PF-403-readonly-token', 'op' => 'PutFile', 'requirement' => 'PutFile with a read-only (canwrite=false) token returns 403', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-403-fileid-mismatch', 'op' => 'PutFile', 'requirement' => 'PutFile returns 403 when the token\'s fileId does not match {fileId}', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-401-expired-token', 'op' => 'PutFile', 'requirement' => 'PutFile with an expired token returns 401', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-403-unknown-token', 'op' => 'PutFile', 'requirement' => 'PutFile with an unknown token returns 403', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-404-file-not-found', 'op' => 'PutFile', 'requirement' => 'PutFile returns 404 when the underlying file cannot be resolved', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-507-insufficient-storage', 'op' => 'PutFile', 'requirement' => 'PutFile returns 507 when Content-Length exceeds available free space', 'spec' => 'MS-WOPI PutFile', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived'],
	['id' => 'PF-fclose-guard', 'op' => 'PutFile', 'requirement' => 'fclose() on php://input is guarded with is_resource() since putContent() may close it internally', 'spec' => 'N/A - regression guard', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'NC35 compatibility fix, WOPI_TEST_RESULTS.md Compatibility Fixes table'],

	// --- Lock-operation dispatch (executeOperation) ---
	['id' => 'EXECOP-403-readonly-all-overrides', 'op' => 'Lock dispatch', 'requirement' => 'Any X-WOPI-Override on a read-only (canwrite=false) token returns 403 before dispatch, for all five overrides', 'spec' => 'MS-WOPI Lock/Unlock/RefreshLock/GetLock/RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testAllOverridesReturn403WhenTokenCannotWrite', 'notes' => 'security fix 51e4fc5'],
	['id' => 'EXECOP-501-unknown-override', 'op' => 'Lock dispatch', 'requirement' => 'An unrecognized X-WOPI-Override returns 501 "Unsupported WOPI operation"', 'spec' => 'MS-WOPI', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnknownOverrideReturns501', 'notes' => 'code-derived'],
	['id' => 'EXECOP-403-fileid-mismatch', 'op' => 'Lock dispatch', 'requirement' => 'executeOperation returns 403 when the token\'s fileId does not match {fileId}', 'spec' => 'MS-WOPI', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testExecuteOperationReturns403WhenFileIdMismatch', 'notes' => 'code-derived'],
	['id' => 'EXECOP-401-expired-token', 'op' => 'Lock dispatch', 'requirement' => 'executeOperation with an expired token returns 401', 'spec' => 'MS-WOPI', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testExecuteOperationReturns401WhenTokenExpired', 'notes' => 'code-derived'],
	['id' => 'EXECOP-403-unknown-token', 'op' => 'Lock dispatch', 'requirement' => 'executeOperation with an unknown token returns 403', 'spec' => 'MS-WOPI', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testExecuteOperationReturns403WhenTokenUnknown', 'notes' => 'code-derived'],

	// --- LOCK ---
	['id' => 'LOCK-200-new', 'op' => 'Lock', 'requirement' => 'LOCK on an unlocked file returns 200', 'spec' => 'MS-WOPI Lock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testLockFreshReturns200', 'notes' => 'WOPI_TEST_RESULTS.md row 7'],
	['id' => 'LOCK-400-empty-lockid', 'op' => 'Lock', 'requirement' => 'LOCK with an empty X-WOPI-Lock header returns 400', 'spec' => 'MS-WOPI Lock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testLockEmptyIdReturns400', 'notes' => 'code-derived'],
	['id' => 'LOCK-200-relock-same-id-idempotent', 'op' => 'Lock', 'requirement' => 'LOCK with the same lock ID as the existing lock is idempotent (200), refreshing the TTL', 'spec' => 'MS-WOPI Lock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testLockSameIdIsIdempotent', 'notes' => 'WOPI_TEST_RESULTS.md row 10'],
	['id' => 'LOCK-409-different-id', 'op' => 'Lock', 'requirement' => 'LOCK with a different lock ID on an already-locked file returns 409 + X-WOPI-Lock + X-WOPI-LockFailureReason', 'spec' => 'MS-WOPI Lock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testLockDifferentIdReturns409WithBothHeaders', 'notes' => 'WOPI_TEST_RESULTS.md row 9'],
	['id' => 'LOCK-200-unlockandrelock-valid', 'op' => 'Lock (UnlockAndRelock)', 'requirement' => 'LOCK + X-WOPI-OldLock matching the current lock replaces it with the new lock ID, 200', 'spec' => 'MS-WOPI UnlockAndRelock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockAndRelockValidReturns200', 'notes' => 'WOPI_TEST_RESULTS.md row 17'],
	['id' => 'LOCK-409-unlockandrelock-wrong-old', 'op' => 'Lock (UnlockAndRelock)', 'requirement' => 'LOCK + X-WOPI-OldLock not matching the current lock returns 409 + current lock + X-WOPI-LockFailureReason', 'spec' => 'MS-WOPI UnlockAndRelock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockAndRelockWrongOldReturns409', 'notes' => 'WOPI_TEST_RESULTS.md row 18'],
	['id' => 'LOCK-409-unlockandrelock-no-existing-lock', 'op' => 'Lock (UnlockAndRelock)', 'requirement' => 'LOCK + X-WOPI-OldLock when no lock currently exists returns 409', 'spec' => 'MS-WOPI UnlockAndRelock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockAndRelockWithNoExistingLockReturns409', 'notes' => 'code-derived'],
	['id' => 'LOCK-expired-treated-as-absent', 'op' => 'Lock', 'requirement' => 'An expired existing lock is treated as absent, so a fresh LOCK succeeds (200) instead of 409', 'spec' => 'MS-WOPI Lock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testExpiredExistingLockTreatedAsAbsentOnLock', 'notes' => 'code-derived'],

	// --- UNLOCK ---
	['id' => 'UNLOCK-200', 'op' => 'Unlock', 'requirement' => 'UNLOCK with the matching lock ID returns 200', 'spec' => 'MS-WOPI Unlock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockOkReturns200', 'notes' => 'WOPI_TEST_RESULTS.md row 12'],
	['id' => 'UNLOCK-400-empty-lockid', 'op' => 'Unlock', 'requirement' => 'UNLOCK with an empty X-WOPI-Lock header returns 400', 'spec' => 'MS-WOPI Unlock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockEmptyIdReturns400', 'notes' => 'code-derived'],
	['id' => 'UNLOCK-409-wrong-id', 'op' => 'Unlock', 'requirement' => 'UNLOCK with a non-matching lock ID returns 409 + current lock + X-WOPI-LockFailureReason', 'spec' => 'MS-WOPI Unlock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockWrongIdReturns409', 'notes' => 'code-derived'],
	['id' => 'UNLOCK-409-no-existing-lock', 'op' => 'Unlock', 'requirement' => 'UNLOCK when no lock currently exists returns 409 with an empty X-WOPI-Lock', 'spec' => 'MS-WOPI Unlock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testUnlockWithNoExistingLockReturns409', 'notes' => 'code-derived'],

	// --- REFRESH_LOCK ---
	['id' => 'REFRESH-200', 'op' => 'RefreshLock', 'requirement' => 'REFRESH_LOCK with the matching lock ID returns 200, extending the TTL', 'spec' => 'MS-WOPI RefreshLock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRefreshLockOkReturns200', 'notes' => 'WOPI_TEST_RESULTS.md row 11'],
	['id' => 'REFRESH-400-empty-lockid', 'op' => 'RefreshLock', 'requirement' => 'REFRESH_LOCK with an empty X-WOPI-Lock header returns 400', 'spec' => 'MS-WOPI RefreshLock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRefreshLockEmptyIdReturns400', 'notes' => 'code-derived'],
	['id' => 'REFRESH-409-mismatch', 'op' => 'RefreshLock', 'requirement' => 'REFRESH_LOCK with a non-matching lock ID returns 409 + current lock + X-WOPI-LockFailureReason', 'spec' => 'MS-WOPI RefreshLock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRefreshLockMismatchReturns409', 'notes' => 'code-derived'],

	// --- GET_LOCK ---
	['id' => 'GETLOCK-200-with-lock', 'op' => 'GetLock', 'requirement' => 'GET_LOCK on a locked file returns 200 + X-WOPI-Lock: <id>', 'spec' => 'MS-WOPI GetLock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testGetLockWithLockReturnsLockHeader', 'notes' => 'WOPI_TEST_RESULTS.md row 8'],
	['id' => 'GETLOCK-200-empty-when-unlocked', 'op' => 'GetLock', 'requirement' => 'GET_LOCK on an unlocked file returns 200 + X-WOPI-Lock: "" (empty, per spec, not 404/409)', 'spec' => 'MS-WOPI GetLock', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testGetLockWithoutLockReturnsEmptyHeader', 'notes' => 'WOPI_TEST_RESULTS.md row 13'],

	// --- RenameFile ---
	['id' => 'RENAME-200-success', 'op' => 'RenameFile', 'requirement' => 'RENAME_FILE with a valid, non-colliding name returns 200 + Name', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileSuccessReturns200WithName', 'notes' => 'code-derived; zero coverage in WOPI_TEST_RESULTS.md, added explicitly for Task 4'],
	['id' => 'RENAME-403-guest', 'op' => 'RenameFile', 'requirement' => 'RENAME_FILE from a guest token returns 403', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileGuestReturns403', 'notes' => 'code-derived'],
	['id' => 'RENAME-400-empty-requested-name', 'op' => 'RenameFile', 'requirement' => 'RENAME_FILE with an empty X-WOPI-RequestedName returns 400', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileEmptyRequestedNameReturns400', 'notes' => 'code-derived'],
	['id' => 'RENAME-400-path-traversal-slash-or-null', 'op' => 'RenameFile', 'requirement' => 'A UTF-7-decoded name containing "/" or a null byte is rejected with 400 + X-WOPI-InvalidFileNameError', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileRejectsPathTraversalSlashOrNullByte', 'notes' => 'C-1 path-traversal fix, commit 71e4f08'],
	['id' => 'RENAME-backslash-not-rejected-by-basename-guard', 'op' => 'RenameFile', 'requirement' => 'A UTF-7-decoded name containing "\\" (e.g. "..\\..\\evil") is NOT rejected by the current basename()-based guard, since basename() only treats "/" as a separator on non-Windows PHP', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileDoesNotRejectBackslashTraversal', 'notes' => 'Verified: basename(\'..\\..\\evil.docx\') === \'..\\..\\evil.docx\' on this PHP build. Whether it is actually exploitable depends on how NC\'s storage layer resolves the resulting path (it splits on "/", not "\\") - Task 4 documents current behavior, does not fix lib/.'],
	['id' => 'RENAME-400-name-collision', 'op' => 'RenameFile', 'requirement' => 'A requested name that already exists in the same folder returns 400 + X-WOPI-InvalidFileNameError', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileNameCollisionReturns400', 'notes' => 'code-derived'],
	['id' => 'RENAME-409-lock-mismatch', 'op' => 'RenameFile', 'requirement' => 'RENAME_FILE on a locked file with a non-matching X-WOPI-Lock returns 409', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileLockMismatchReturns409', 'notes' => 'code-derived'],
	['id' => 'RENAME-404-file-not-found', 'op' => 'RenameFile', 'requirement' => 'RENAME_FILE returns 404 when the underlying file cannot be resolved', 'spec' => 'MS-WOPI RenameFile', 'status' => 'tested', 'test' => 'unit/Controller/WopiControllerLockTest::testRenameFileFileNotFoundReturns404', 'notes' => 'code-derived'],

	// --- Admin Settings (app-specific, seeded from WOPI_TEST_RESULTS.md anyway) ---
	['id' => 'SETTINGS-200-get-admin', 'op' => 'Admin Settings', 'requirement' => 'GET admin settings returns 200 + wopi_url for an authenticated admin', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/AdminSettingsTest::testGetAdminSettingsReturnsConfigForAdmin', 'notes' => 'WOPI_TEST_RESULTS.md row 19'],
	['id' => 'SETTINGS-400-invalid-scheme', 'op' => 'Admin Settings', 'requirement' => 'POST admin settings with an invalid URL scheme (e.g. file://) returns 400', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/AdminSettingsTest::testPostAdminSettingsRejectsInvalidScheme', 'notes' => 'WOPI_TEST_RESULTS.md row 20'],
	['id' => 'SETTINGS-post-valid-resets-discovery-cache', 'op' => 'Admin Settings', 'requirement' => 'Saving valid admin settings calls DiscoveryService::resetCache() so a changed wopi_url is not masked by the cached discovery document', 'spec' => 'N/A - app-specific', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'code-derived, SettingsController.php:73; DiscoveryService::resetCache() itself has a passing unit test (DiscoveryServiceTest::testResetCacheRemovesCacheKey) but the controller call site does not'],

	// --- EditorController (app-specific) ---
	['id' => 'EDITOR-200-open-url', 'op' => 'EditorController', 'requirement' => 'GET /apps/office/open?fileId={id} for an authenticated session returns 200 + editorUrl containing wopisrc and access_token', 'spec' => 'N/A - app-specific', 'status' => 'implemented-untested', 'test' => null, 'notes' => 'WOPI_TEST_RESULTS.md row 21 - NOT reproducible in this environment (verified live in Task 6): EO currently advertises zero editor actions, so getUrlSrc() always returns null and /open always answers 415, never 200. See integration/EditorControllerTest.php docblock. Only the 401/404 branches are integration-tested here (testOpenReturns401WithoutAuth, testOpenReturns404ForNonexistentFile); the 415-given-current-EO-state branch is tested by testOpenReturns415GivenEosCurrentZeroActionDiscovery. The 200 happy path is covered at the unit level instead via DiscoveryServiceTest fixtures.'],
	['id' => 'EDITOR-401-no-auth', 'op' => 'EditorController', 'requirement' => 'GET /open without authentication returns 401', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/EditorControllerTest::testOpenReturns401WithoutAuth', 'notes' => 'code-derived'],
	['id' => 'EDITOR-404-file-not-found', 'op' => 'EditorController', 'requirement' => 'GET /open?fileId={id} for a nonexistent file returns 404', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/EditorControllerTest::testOpenReturns404ForNonexistentFile', 'notes' => 'code-derived'],

	// --- Share/guest token flow (ShareController + TokenManager::generateGuestToken) ---
	['id' => 'SHARE-404-unknown-token', 'op' => 'ShareController', 'requirement' => 'GET /open/share/{token} with an unknown share token returns 404', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/ShareGuestTokenTest::testOpenShareReturns404ForUnknownToken', 'notes' => 'code-derived'],
	['id' => 'SHARE-guest-proceeds-without-password', 'op' => 'ShareController', 'requirement' => 'An unauthenticated guest visiting a share link that has NO password proceeds past the password guard (does not get redirected to the generic share page)', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/ShareGuestTokenTest::testOpenShareLetsUnauthenticatedGuestProceedWithoutPassword', 'notes' => 'FIXED (was SHARE-guest-blocked-by-password-check-bug): ShareController::openShare() used to guard with `$share->getPassword() !== \'\'`. IShare::getPassword() returns string|null and is null (not \'\') for a passwordless share, and `null !== \'\'` is true in PHP, so the guard fired for password-LESS shares too - any unauthenticated guest on a share that was never password-protected got redirected to the generic NC share page (303) instead of ever reaching the editor, and it silently masked every branch after it for unauthenticated requests too (see SHARE-403-unreadable-share). Fixed in ShareController.php:79 to treat null and \'\' both as "no password". Observable result in this environment is 415 (EO advertises zero editor actions), not the historical 200 - see EDITOR-200-open-url.'],
	['id' => 'SHARE-authenticated-bypasses-password-check', 'op' => 'ShareController', 'requirement' => 'An authenticated (non-guest) visitor to a share link skips the password-check branch entirely, reaching the discovery-dependent editor URL code', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/ShareGuestTokenTest::testOpenShareAuthenticatedUserBypassesPasswordCheckButHitsEoDiscoveryLimitation', 'notes' => 'Same EO-zero-actions environment limitation as EDITOR-200-open-url applies here too - resolves to 415, not 200, in this environment'],
	['id' => 'SHARE-403-unreadable-share', 'op' => 'ShareController', 'requirement' => 'A share with no READ permission returns 403', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/ShareGuestTokenTest::testOpenShareReturns403ForUnreadableShareAsUnauthenticatedGuest', 'notes' => 'Was only reachable via an AUTHENTICATED request before the SHARE-guest-proceeds-without-password fix - an unauthenticated guest used to hit the password-check bug first (303) and never reach this guard. Now tested directly as an unauthenticated guest, matching the fixed behavior.'],
	['id' => 'SHARE-guest-token-grants-anonymous-wopi-access', 'op' => 'TokenManager (guest)', 'requirement' => 'A guest token issued via TokenManager::generateGuestToken() grants working, read-scoped, download-hidden WOPI access (IsAnonymousUser, UserFriendlyName, UserCanWrite, HideExportOption/DisablePrint)', 'spec' => 'MS-WOPI CheckFileInfo (guest)', 'status' => 'tested', 'test' => 'integration/ShareGuestTokenTest::testGuestTokenGrantsAnonymousWopiAccess', 'notes' => 'Issues the token directly (as WOPI_TEST_RESULTS.md\'s own Phase 1/2 methodology did) rather than via the currently-broken ShareController HTTP entry point above - this verifies the underlying guest-token WOPI mechanics work correctly, independent of that bug'],

	// --- Routing / background jobs (app-specific) ---
	['id' => 'ROUTE-index-php-prefix', 'op' => 'Routing', 'requirement' => 'linkToRouteAbsolute() for WOPI routes includes the /index.php/ prefix in this dev setup', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/RouteTest::testWopiRouteIncludesIndexPhpPrefix', 'notes' => 'WOPI_TEST_RESULTS.md unnumbered Route check'],
	['id' => 'CLEANUPJOB-registered', 'op' => 'CleanupJob', 'requirement' => 'OCA\\Office\\BackgroundJob\\CleanupJob is registered and appears in occ background-job:list', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/CleanupJobTest::testCleanupJobIsRegisteredInJobList', 'notes' => 'WOPI_TEST_RESULTS.md unnumbered CleanupJob check'],
	['id' => 'CLEANUPJOB-purges-expired-tokens-and-locks', 'op' => 'CleanupJob', 'requirement' => 'Invoking CleanupJob::run() deletes expired WOPI tokens (WopiMapper::getExpiredTokenIds/deleteByIds) and expired locks (WopiLockMapper::getExpiredLockIds/deleteByIds), batched at 500', 'spec' => 'N/A - app-specific', 'status' => 'tested', 'test' => 'integration/CleanupJobTest::testCleanupJobPurgesExpiredToken', 'notes' => 'code-derived, lib/BackgroundJob/CleanupJob.php - not exercised by the occ list check above, which only confirms registration'],

	// --- Explicitly not implemented (visibility on the gap, per plan) ---
	['id' => 'SPEC-putrelativefile-not-implemented', 'op' => 'PutRelativeFile', 'requirement' => 'Save As / relative-file creation from the editor', 'spec' => 'MS-WOPI PutRelativeFile', 'status' => 'not-implemented', 'test' => null, 'notes' => 'CheckFileInfo already advertises UserCanNotWriteRelative=true; deferred to Phase 6 per WopiController.php comment'],
	['id' => 'SPEC-deletefile-not-implemented', 'op' => 'DeleteFile', 'requirement' => 'Delete the file being edited, from the editor', 'spec' => 'MS-WOPI DeleteFile', 'status' => 'not-implemented', 'test' => null, 'notes' => null],
	['id' => 'SPEC-putuserinfo-not-implemented', 'op' => 'PutUserInfo', 'requirement' => 'Persist arbitrary per-user editor state via the host', 'spec' => 'MS-WOPI PutUserInfo', 'status' => 'not-implemented', 'test' => null, 'notes' => null],
	['id' => 'SPEC-proofkey-validation-not-implemented', 'op' => 'Proof Keys', 'requirement' => 'Validate X-WOPI-Proof / X-WOPI-ProofOld headers to authenticate that a request genuinely came from the editor server', 'spec' => 'MS-WOPI Proof Keys', 'status' => 'not-implemented', 'test' => null, 'notes' => 'Any caller holding a valid access_token is trusted; no proof-key check anywhere in WopiController'],
	['id' => 'SPEC-itemversion-completeness-not-implemented', 'op' => 'ItemVersion', 'requirement' => 'X-WOPI-ItemVersion returned consistently across Lock/Unlock/RefreshLock/GetLock responses, not just PutFile', 'spec' => 'MS-WOPI ItemVersion (optional)', 'status' => 'not-implemented', 'test' => null, 'notes' => 'Optional per spec, but currently only PutFile ever sets X-WOPI-ItemVersion'],
	['id' => 'SPEC-access-token-form-post-not-implemented', 'op' => 'Access Token Delivery', 'requirement' => 'Accept access_token via an application/x-www-form-urlencoded POST body, as an alternative to the ?access_token= query parameter', 'spec' => 'MS-WOPI Access Tokens', 'status' => 'not-implemented', 'test' => null, 'notes' => 'Every WopiController action reads access_token as a route/query parameter only'],
];
